<section class="page_a_propos">

    <div class="page_title_strap">
        <h1 class="page_title">À propros</h1>
    </div>

    <div class="page_content">
        <div class="page_hentry widzmain">
            <h2 class="title">Parcours</h2>
                <p>Après avoir suivi une formation en tant que Développeur Intégrateur Web à la 3W Academy, j'ai choisi de me spécialiser davantage dans le domaine de l'intégration Web en rejoignant l'agence Kalelia. Pendant plus d'un an, j'ai occupé le poste d'intégratrice web, où ma principale mission était de donner vie aux maquettes graphiques en utilisant des langages tels que HTML, CSS, JS et PHP. Par la suite, j'ai suivi une formation en tant que Développeur Salesforce, mais ayant toujours eu une préférence pour le côté "créatif", j'ai décidé de ne pas poursuivre dans cette voie. Je suis actuellement en poste depuis un peu plus d'an an au sein de l'agence de communication Groupe Echo en tant qu'intégratice web.</p>
            <a href="https://www.linkedin.com/in/elodiefontaine1897/" target="_blank">Découvrir mon linkedin</a>
        </div>
    </div>

    <div class="widzmain">
        <h2 class="title">Mes loisirs</h2>
        <div>
        <aside class="home_competence_list loisir">
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Lecture (Roman, Manga, BD)
				</p>
			</article>
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Photographie
				</p>
			</article>
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Cuisine
				</p>
			</article>
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Culture Japonais (apprendissage de la langue)
				</p>
			</article>
		</aside>
        </div>
    </div>

</section>