<section>

	<div class="page_title_strap">
		<h1 class="page_title title">Elodie Fontaine, <br> Intégratrice Web</h1>
	</div>

</section>

<section class="rea">

	<div class="rea_list widzmain">
		<div class="rea_single_list">
			<?php foreach($posts as $post): ?>
			<article class="rea_content_single" style="background-image: url('<?='img/post/'.$post['picture'] ?>')">
				<div class="rea_single_list_hover">
					<div class="rea_inlist_main">
						<h2 class="rea_single_list_title title"><?= $post['title'] ?></h2>
						<p class="single_post_cat"><?= $post['name'] ?></p>
					</div>
				</div>
				<a class="rea_single_list_link" href="<?= $path ?>controllers/show_post.php?id=<?= intval($post['id']) ?>"></a>
			</article>
			<?php endforeach; ?>
		</div>
	</div>

	<div class="rea_btn">
		<a class="rea_link" href="controllers/realisation.php">
			<span class="rea_link_span">Voir toutes les réalisations</span>
		</a>
	</div>

</section>

<section class="home_competence">
	<div class="widzmain">
		<h2 class="title home_competence_title">
			Compétences
		</h2>
		<aside class="home_competence_list">
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Intégration des maquettes sur Wordpress et E-majine
				</p>
			</article>
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Intégration de site sur-mesure sur le CMS Wordpress
				</p>
			</article>
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Langage HTML, CSS, JavaScript, PHP, jQuery
				</p>
			</article>
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Développement front et back office
				</p>
			</article>
			<article class="home_competence_list_single">
				<p class="home_competence_single_txt">
					Création design site avec le constructeur de thème Divi (sur-mesure ou catalogue)
				</p>
			</article>
		</aside>
	</div>
</section>